version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: game-postgres
    restart: always
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: game
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
