// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/buildings": {
            "get": {
                "description": "Zwraca listę budynków i ich poziomów w wybranej wiosce",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Pobierz budynki wioski",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID wioski",
                        "name": "village_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing or invalid village_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/buildings/cost": {
            "get": {
                "description": "Zwraca koszt następnego poziomu dla podanego budynku",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Pobierz koszt ulepszenia budynku",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID wioski",
                        "name": "village_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Typ budynku (np. lumbermill, claypit, ironmine, warehouse, barracks)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing params or invalid village_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Building not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/buildings/upgrade": {
            "put": {
                "description": "Podnosi poziom budynku, jeśli gracza stać na koszt",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Ulepsz budynek",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID wioski",
                        "name": "village_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Typ budynku (np. lumbermill, claypit, ironmine, warehouse, barracks)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing params or invalid village_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Not enough resources",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Building not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Zwraca token JWT po poprawnym zalogowaniu",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logowanie użytkownika",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nazwa użytkownika",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Hasło",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Nie unieważnia tokena – klient powinien go odrzucić po stronie frontendu",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Wylogowanie użytkownika",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Tworzy nowego użytkownika wraz ze startową wioską, zasobami, budynkami i jednostkami",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rejestracja użytkownika",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nazwa użytkownika",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Adres e-mail",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Hasło (min 8 znaków, wielka, mała, cyfra, znak specjalny)",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "User exists or DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/resources": {
            "get": {
                "description": "Zwraca aktualny stan zasobów w wiosce. Produkcja zasobów jest liczona dynamicznie na podstawie poziomu budynków (lumbermill, claypit, ironmine) i czasu, jaki minął od ostatniej aktualizacji.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Pobierz zasoby wioski",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID wioski",
                        "name": "village_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing or invalid village_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Resources not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/units": {
            "get": {
                "description": "Zwraca listę jednostek i ich liczebność w wybranej wiosce",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "Pobierz jednostki w wiosce",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID wioski",
                        "name": "village_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing or invalid village_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/units/recruit": {
            "post": {
                "description": "Rekrutuje jednostki w wiosce, o ile użytkownik posiada wystarczające zasoby.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "Rekrutuj jednostki",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID wioski",
                        "name": "village_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Typ jednostki (spearman, swordsman, archer)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Liczba rekrutowanych jednostek",
                        "name": "count",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing params or invalid unit type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Not enough resources or village not yours",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/villages": {
            "get": {
                "description": "Zwraca listę wiosek należących do zalogowanego użytkownika",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "villages"
                ],
                "summary": "Pobierz wszystkie wioski użytkownika",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.Village"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Tworzy nową wioskę, jeśli użytkownik spełnia wymagania Townhallu",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "villages"
                ],
                "summary": "Utwórz nową wioskę",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nazwa nowej wioski",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing village name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "You need higher Townhall level",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/villages/{id}": {
            "put": {
                "description": "Aktualizuje nazwę wioski, jeśli należy do użytkownika",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "villages"
                ],
                "summary": "Zmień nazwę wioski",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Village ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nowa nazwa wioski",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid village ID or missing name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Village not yours",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Usuwa wioskę użytkownika, wraz z powiązanymi danymi",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "villages"
                ],
                "summary": "Usuń wioskę",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Village ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid village ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Village not yours",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.Village": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Game API",
	Description:      "Strategy game backend with users, villages, resources, buildings, and units.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
